# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d883e2c2ae19614a67878e788d8d09c318549368b0ce185d427eae7524350895edc899e6d49078b4ab0971f55b6d9cc87f51a611b93c6a81a495f3cf4bdd067

test:
  secret_key_base: e2376db52099b91581dd91c958040276344ced56071ac23877a6963aae3f6f3896937db38dbb1e19b182b2424cd3c0c1700d28896f682f396b5d7c55d3c06e0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
